[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["麦麦 <15009897+awslman@user.noreply.gitee.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
nltk = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
